swagger: "2.0"
info:
  title: "Banner swagger service"
  description: "Offers functionality to return ascii rendered banners"
  version: "1.0.0"

consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /health:
    get:
      tags: [health]
      operationId: app.health.health
      summary: Health Check
      responses:
        '200':
          description: Status message for current health

  /ready:
    get:
      tags: [ready]
      operationId: app.ready.ready
      summary: Readiness Check
      responses:
        '200':
          description: Status message for current readiness

  /banner:
    get:
      consumes:
        - text/plain       
      produces:
        - text/plain
      operationId: "app.banner.generate"
      parameters:
        - name: message
          description: Message to render.
          in: query
          type: "string"
          required: true
        - name: fontname
          description: Font to use.
          in: query
          type: "string"
          required: true
        - name: width
          description: Width of terminal
          in: query
          type: "integer"
          default: 0
          required: false          
      tags:
        - "banner"
      summary: "Will return the banner as a plain text ansi string"
      description: "Generate the banner"
      responses:
        200:
          description: 'OK'
          schema:
            type: string
        400:
          description: 'Font not found'
          schema:
            type: string

  /fonts:
    get:
      consumes:
        - application/json       
      produces:
        - application/json
      operationId: "app.banner.supported_fonts"
      summary: "Will return the supported fonts"
      description: "Supported fonts"
      responses:
        '200':
          description: 'Array of font names.'
          schema:
            type: "array"
            items:
              properties:
                name:
                  type: "string"
